spring:
  application:
    name: seata-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.70:3306/seata_user?useUnicode=true&characterEncoding=utf-8
    username: root
    password: leon

server:
  port: 8093

management:
  endpoints:
    web:
      exposure:
        include: "*"

mybatis:
  type-aliases-package: com.zhao.seata.user.mapper
  mapper-locations: classpath:*.xml